import 'package:flutter/material.dart';
import 'package:get/get.dart';
import '../../data/models/patient_model.dart';
import '../shared_widgets/custom_text_field.dart';
import 'patients_controller.dart';

class AddPatientView extends StatefulWidget {
  const AddPatientView({super.key});

  @override
  State<AddPatientView> createState() => _AddPatientViewState();
}

class _AddPatientViewState extends State<AddPatientView> {
  final _formKey = GlobalKey<FormState>();
  final PatientsController _controller = Get.find<PatientsController>();

  // Text Controllers
  final _nameController = TextEditingController();
  final _ageController = TextEditingController();
  final _conditionController = TextEditingController();
  final _notesController = TextEditingController();

  // Dropdown States
  String _selectedGender = 'Male';
  String _selectedStatus = 'Stable';

  @override
  void dispose() {
    _nameController.dispose();
    _ageController.dispose();
    _conditionController.dispose();
    _notesController.dispose();
    super.dispose();
  }

  Future<void> _submitForm() async {
    if (_formKey.currentState!.validate()) {
      final name = _nameController.text.trim();
      final age = int.tryParse(_ageController.text.trim()) ?? 0;
      final condition = _conditionController.text.trim();
      final notes = _notesController.text.trim();

      // Create Patient object with nested structure placeholders (for details screen simulation)
      final patient = Patient(
        id: '', // Generated by backend/service
        name: name,
        age: age,
        gender: _selectedGender,
        condition: condition,
        status: _selectedStatus,
        notes: notes.isNotEmpty ? notes : null,
        medicalHistory: ['Admitted on 2026-07-15 for $condition'],
        prescriptions: [
          {
            'medication': 'Rx Gen-Med',
            'dosage': 'Daily',
            'frequency': 'Morning',
          },
        ],
        labReports: [
          {
            'test': 'Admittance Screening',
            'result': 'Pending Analysis',
            'date': '2026-07-15',
          },
        ],
      );

      final success = await _controller.addPatient(patient);
      if (success) {
        Get.back(); // Pop the form screen on success
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Scaffold(
      appBar: AppBar(
        title: const Text('Add Patient Record'),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          onPressed: () => Get.back(),
        ),
      ),
      body: Stack(
        children: [
          SingleChildScrollView(
            padding: const EdgeInsets.all(16.0),
            child: Form(
              key: _formKey,
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  // Instruction Card
                  Container(
                    width: double.infinity,
                    padding: const EdgeInsets.all(12),
                    margin: const EdgeInsets.only(bottom: 20),
                    decoration: BoxDecoration(
                      color: theme.primaryColor.withOpacity(0.05),
                      borderRadius: BorderRadius.circular(12),
                      border: Border.all(
                        color: theme.primaryColor.withOpacity(0.15),
                      ),
                    ),
                    child: Row(
                      children: [
                        Icon(Icons.info_outline, color: theme.primaryColor),
                        const SizedBox(width: 12),
                        const Expanded(
                          child: Text(
                            'Please double-check all clinical data fields. Records are synced directly to clinic databases.',
                            style: TextStyle(
                              fontSize: 13,
                              fontWeight: FontWeight.w500,
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),

                  // Name Field
                  CustomTextField(
                    controller: _nameController,
                    labelText: 'Full Name',
                    hintText: 'e.g., John Doe',
                    prefixIcon: Icons.person_outline,
                    validator: (val) {
                      if (val == null || val.trim().isEmpty) {
                        return 'Patient name is required';
                      }
                      return null;
                    },
                  ),
                  const SizedBox(height: 16),

                  // Age Field
                  CustomTextField(
                    controller: _ageController,
                    labelText: 'Age',
                    hintText: 'e.g., 34',
                    prefixIcon: Icons.calendar_today_outlined,
                    keyboardType: TextInputType.number,
                    validator: (val) {
                      if (val == null || val.trim().isEmpty) {
                        return 'Patient age is required';
                      }
                      if (int.tryParse(val.trim()) == null) {
                        return 'Please enter a valid age number';
                      }
                      return null;
                    },
                  ),
                  const SizedBox(height: 16),

                  // Gender Dropdown
                  Text(
                    'Gender',
                    style: theme.textTheme.titleSmall?.copyWith(
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: 8),
                  DropdownButtonFormField<String>(
                    value: _selectedGender,
                    decoration: InputDecoration(
                      prefixIcon: Icon(
                        Icons.wc_outlined,
                        color: theme.colorScheme.primary.withOpacity(0.8),
                      ),
                    ),
                    items: const [
                      DropdownMenuItem(value: 'Male', child: Text('Male')),
                      DropdownMenuItem(value: 'Female', child: Text('Female')),
                      DropdownMenuItem(value: 'Other', child: Text('Other')),
                    ],
                    onChanged: (val) {
                      if (val != null) {
                        setState(() {
                          _selectedGender = val;
                        });
                      }
                    },
                  ),
                  const SizedBox(height: 16),

                  // Condition Field
                  CustomTextField(
                    controller: _conditionController,
                    labelText: 'Medical Condition',
                    hintText: 'e.g., Hypertension / Diabetic screening',
                    prefixIcon: Icons.healing_outlined,
                    validator: (val) {
                      if (val == null || val.trim().isEmpty) {
                        return 'Diagnosis/Condition is required';
                      }
                      return null;
                    },
                  ),
                  const SizedBox(height: 16),

                  // Status Dropdown
                  Text(
                    'Clinical Status Badge',
                    style: theme.textTheme.titleSmall?.copyWith(
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: 8),
                  DropdownButtonFormField<String>(
                    value: _selectedStatus,
                    decoration: InputDecoration(
                      prefixIcon: Icon(
                        Icons.rule_folder_outlined,
                        color: theme.colorScheme.primary.withOpacity(0.8),
                      ),
                    ),
                    items: const [
                      DropdownMenuItem(value: 'Stable', child: Text('Stable')),
                      DropdownMenuItem(
                        value: 'Critical',
                        child: Text('Critical'),
                      ),
                    ],
                    onChanged: (val) {
                      if (val != null) {
                        setState(() {
                          _selectedStatus = val;
                        });
                      }
                    },
                  ),
                  const SizedBox(height: 16),

                  // Notes Textarea
                  CustomTextField(
                    controller: _notesController,
                    labelText: 'Notes / Additional Symptoms (Optional)',
                    hintText: 'Enter clinical observations or comments...',
                    prefixIcon: Icons.notes_outlined,
                    maxLines: 4,
                  ),
                  const SizedBox(height: 32),

                  // Buttons Actions
                  Row(
                    children: [
                      Expanded(
                        child: OutlinedButton(
                          onPressed: () => Get.back(),
                          style: OutlinedButton.styleFrom(
                            padding: const EdgeInsets.symmetric(vertical: 16),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(12),
                            ),
                          ),
                          child: const Text('Cancel'),
                        ),
                      ),
                      const SizedBox(width: 16),
                      Expanded(
                        child: ElevatedButton(
                          onPressed: _submitForm,
                          style: ElevatedButton.styleFrom(
                            padding: const EdgeInsets.symmetric(vertical: 16),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(12),
                            ),
                          ),
                          child: const Text('Submit Record'),
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 40),
                ],
              ),
            ),
          ),

          // Loading Overlay indicator
          Obx(() {
            if (_controller.isLoading.value) {
              return Container(
                color: Colors.black26,
                child: const Center(
                  child: Card(
                    child: Padding(
                      padding: EdgeInsets.symmetric(
                        horizontal: 24,
                        vertical: 20,
                      ),
                      child: Column(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          CircularProgressIndicator(),
                          SizedBox(height: 16),
                          Text(
                            'Synching patient file...',
                            style: TextStyle(fontWeight: FontWeight.bold),
                          ),
                          Text(
                            'Simulating API POST delay...',
                            style: TextStyle(fontSize: 12, color: Colors.grey),
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
              );
            }
            return const SizedBox.shrink();
          }),
        ],
      ),
    );
  }
}
